version: '3'

services:
  nextjs-app:
    build:
      context: ./Nextjs
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./Nextjs/login-check:/app
      - /app/node_modules
      - /app/.next

  db:
    build: 
      context: ./MySQL
      dockerfile: Dockerfile
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
    volumes:
      - ./MySQL/init:/docker-entrypoint-initdb.d/
